In [2]:
#function definition
def message():
    print("I am a funtion")
#function calling
message()

I am a funtion


In [6]:
#write a program to create a function which perform a task of adding two numbers and displaying the result
def add(num1,num2):
    num3 = num1+num2
    print("Result",num3)
#passing the arguments(actual values[num1=4,num2=5]    
add(4,5)    
 

Result 9


In [7]:
#write a program with a function which accepts name, course and display them
def info(name,course):
    print("Name:",name)
    print("Course:",course)

info("IRET","JAVA")    

Name: IRET
Course: JAVA


In [10]:
#employment
def emp_info(emp_id,emp_name,emp_dept):
    print("Employee ID",emp_id)
    print("Employee Name",emp_name)
    print("Employee Dept",emp_dept)
emp_info(107,"James Bond","Science")    

Employee ID 107
Employee Name James Bond
Employee Dept Science


In [ ]:
#keyword argument
def emp_info(emp_id,emp_name,emp_dept):

In [1]:
# ALL ABOUT NUMPY AND ARRAY
import numpy as np
arr = np.array([10, 20, 30, 40])
print("Array:", arr)
print("Type:", type(arr))

Array: [10 20 30 40]
Type: <class 'numpy.ndarray'>


In [7]:
arr = np.arange(0, 10, 2)
print("array with step size 2:", arr)

array with step size 2: [0 2 4 6 8]


In [8]:
arr = np.arange(0, 10, 3)
print("array with step size 2:", arr)

array with step size 2: [0 3 6 9]


In [12]:
arr = np.arange(10, 20, 3)
print("array with step size 3:", arr)

array with step size 3: [10 13 16 19]


In [13]:
arr = np.arange(10, 20, 2)
print("array with step size 2:", arr)

array with step size 2: [10 12 14 16 18]


In [15]:
arr = np.linspace(0, 1, 8)
print("5 equally spaced numbers between 0 and 1:", arr)

5 equally spaced numbers between 0 and 1: [0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


In [17]:
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
empty = np.empty((2,2))
print("Zeros:", zeros)
print("One:", ones)   
print("Empty", empty)

Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
One: [[1. 1.]
 [1. 1.]
 [1. 1.]]
Empty [[2.12199579e-314 1.16497569e-311]
 [7.07502005e-321 6.95165821e-310]]


In [21]:
#indexing and slicing
arr = np.array([5, 10, 15, 20, 25, 30])
print("Original Array:", arr)
# indexing
print("Element at index 2:", arr[2])
# Slicing
print("Elements from index 1 to 4:", arr[1:5])
print("Every second element:", arr[::2])

print("Elements from start till 3:", arr[:4])
print("Elements from specified index and end at last index", arr[3:])


Original Array: [ 5 10 15 20 25 30]
Element at index 2: 15
Elements from index 1 to 4: [10 15 20 25]
Every second element: [ 5 15 25]
Elements from start till 3: [ 5 10 15 20]
Elements from specified index and end at last index [20 25 30]


In [20]:
#2D array Example
arr2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("2D Array:", arr2d)
print("Element at row 1, col 2:", arr2d[1, 2])
print("First two rows:", arr2d[:2, :])

2D Array: [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at row 1, col 2: 60
First two rows: [[10 20 30]
 [40 50 60]]


In [29]:
arr2 = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print("2D Array\n", arr2)
print("First Element", arr2[0][0])
print("Value 70 ", arr2[1][2])

2D Array
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
First Element 10
Value 70  70


In [32]:
# Aggregate functions in numpy
arr = np.array([10, 20, 30, 40, 50])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Index of Max:", np.argmax(arr))
print("Index of Min:", np.argmin(arr))

Sum: 150
Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Maximum: 50
Minimum: 10
Index of Max: 4
Index of Min: 0


In [33]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Addition:", arr1 + arr2)
print("Subtraction:", arr2 - arr1)
print("Multiplication:", arr1 * arr2)
print("Division:", arr2 / arr1)

Addition: [5 7 9]
Subtraction: [3 3 3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]


In [34]:
arr = np.array([1, 4, 9, 16])
print("Square Root:", np.sqrt(arr))
print("Exponent:", np.exp(arr))
print("Sine:" , np.sin(arr))
print("Logarithm:", np.log(arr))

Square Root: [1. 2. 3. 4.]
Exponent: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
Logarithm: [0.         1.38629436 2.19722458 2.77258872]
